---
title: "tamGenetics_sampleSheets"
author: "Rachel Voyt"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Set E + sequences

```{r}
samplePlate_indexSeqs <- read.csv("./sampleSheet_indexSeqs.csv") %>%
  mutate(I5_Index_ID = gsub("-A", "", I5_Index_ID)) %>%
  mutate(I5_Index_ID = gsub("-B", "", I5_Index_ID)) %>%
  mutate(I5_Index_ID = gsub("-C", "", I5_Index_ID)) %>%
  mutate(I5_Index_ID = gsub("-D", "", I5_Index_ID)) %>%
  mutate(I7_Index_ID = gsub("-A", "", I7_Index_ID)) %>%
  mutate(I7_Index_ID = gsub("-B", "", I7_Index_ID)) %>%
  mutate(I7_Index_ID = gsub("-C", "", I7_Index_ID)) %>%
  mutate(I7_Index_ID = gsub("-D", "", I7_Index_ID)) %>%
  rename("i5" = "I5_Index_ID",
         "i5_index" = "index2",
         "i7" = "I7_Index_ID",
         "i7_index" = "index")
samplePlate_indexSeqs_i5 <- samplePlate_indexSeqs %>%
  select(c("i5", "i5_index")) %>%
  unique()
samplePlate_indexSeqs_i7 <- samplePlate_indexSeqs %>%
  select(c("i7", "i7_index")) %>%
  unique()

indexPlate_setE_i5Seqs <- indexPlate_setE %>%
  select(c("name", "dest_well")) %>%
  filter(str_detect(name, "S5")) %>%
  merge(., samplePlate_indexSeqs_i5, by.x = "name", by.y = "i5", all.x = T) %>%
  mutate(i5_index = 
           case_when(
             name == "S501" ~ "TAGATCGC",
             name == "S504" ~ "AGAGTAGA",
             .default = i5_index
           )
         )

indexPlate_setE_i7Seqs <- indexPlate_setE %>%
  select(c("name", "dest_well")) %>%
  filter(str_detect(name, "N7")) %>%
  merge(., samplePlate_indexSeqs_i7, by.x = "name", by.y = "i7", all.x = T) %>%
  mutate(i7_index = case_when(
           name == "N708" ~ "CAGAGAGG",
           name == "N709" ~ "GCTACGCT",
           .default = i7_index
           )
         )
```

##### for plate 5

```{r}
tamGenetics_plate5_indexSeqs <- indexPlate_setE_i5Seqs %>%
  merge(., indexPlate_setE_i7Seqs, by = "dest_well") %>%
  dplyr::rename("i5" = "name.x",
                "i7" = "name.y") %>%
  arrange(as.numeric(str_sub(dest_well, 2, -1)), str_sub(dest_well, 1, 1)) %>%
  filter(!str_detect(dest_well, "8")) %>%
  filter(!str_detect(dest_well, "9")) %>%
  filter(!str_detect(dest_well, "10")) %>%
  filter(!str_detect(dest_well, "11")) %>%
  filter(!str_detect(dest_well, "12"))


tamGenetics_plate5_indexSeqs_i7 <- indexPrimers_setE %>%
  select(c("i7", "dest_well")) %>%
  head(56)
```
